apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: {{ template "modernpets.name" . }}-jpetstoreweb
    chart: {{ template "modernpets.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "modernpets.name" . }}-jpetstoreweb
    release: {{ .Release.Name }}
  ports:
  - port: 80
    targetPort: 9080

---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: {{ template "modernpets.name" . }}-jpetstoredb
    chart: {{ template "modernpets.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "modernpets.name" . }}-jpetstoredb
    release: {{ .Release.Name }}
  ports:
  - port: 3306
    targetPort: 3306
